name: Zip Crab

on:
  push:
    branches:
    - main
    paths:
    - Avatars/Crab/**

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: Avatars/Crab
          dest: Downloads/Crab.zip
