name: Zip Crab

on:
  push:
    branches:
    - main
    - auto-prepare-downloads
    paths:
    - Avatars/Crab/**
  workflow_dispatch: 

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: Avatars/Crab
          dest: result.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
